/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE avaliacaoBaseService PLEASE EDIT ../avaliacao.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Avaliacao } from '../../domain/aluno-management-portal_db/avaliacao';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../avaliacao.service.ts
 */

/*
 * SCHEMA DB avaliacao
 *
	{
		nota: {
			type: 'Number',
			required : true
		},
		tipo: {
			type: 'String',
			required : true
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		_aluno: {
			type: Schema.ObjectId,
			ref : "avaliacao"
		},
	}
 *
 */
@Injectable()
export class AvaliacaoBaseService {

    contextUrl: string = environment.endpoint + '/avaliacao';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * avaliacaoService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Avaliacao): Observable<Avaliacao> {
        return this.http
            .post<Avaliacao>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * avaliacaoService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * avaliacaoService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): Observable<Avaliacao> {
        return this.http
            .get<Avaliacao>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * avaliacaoService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Avaliacao[]> {
        return this.http
            .get<Avaliacao[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * avaliacaoService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: Avaliacao): Observable<Avaliacao> {
        return this.http
            .post<Avaliacao>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
