/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE cursoBaseService PLEASE EDIT ../curso.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Curso } from '../../domain/aluno-management-portal_db/curso';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../curso.service.ts
 */

/*
 * SCHEMA DB curso
 *
	{
		nome: {
			type: 'String',
			required : true
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		_aluno: {
			type: Schema.ObjectId,
			ref : "curso"
		},
	}
 *
 */
@Injectable()
export class CursoBaseService {

    contextUrl: string = environment.endpoint + '/curso';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * cursoService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Curso): Observable<Curso> {
        return this.http
            .post<Curso>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * cursoService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * cursoService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): Observable<Curso> {
        return this.http
            .get<Curso>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * cursoService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Curso[]> {
        return this.http
            .get<Curso[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * cursoService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: Curso): Observable<Curso> {
        return this.http
            .post<Curso>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
